name: Bug Report
description: File a bug report. Please open one issue per bug found.
title: "[Bug]: "
labels: ["bug"]
type: bug
body:
  - type: checkboxes
    id: type-check
    attributes:
      label: What part of the Framework-Assessment did not work as expected?
      options:
        - label: "finopspp tool"
          required: true
        - label: "assessment workbook"
          required: true
        - label: "markdown file"
          required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: |
        For tools issues, include the output of `finopspp version`. 
        
        For workbook issues, include the release version of the workbook, profile the
        workbook was under, and the Operating System & Version you are running the
        workbook on. 
        
        For markdown file issues, include a github link to where the issue was found in
        the default branch of this repository.
      placeholder: |
        $ finopspp version
        Version: 0.0.2a0
        Python Version: 3.13.7
        System: Linux (6.17.0-8-generic)

        Or

        Release: 0.0.2-alpha
        Profile: FinOps++
        Operating System & Version: Ubuntu 24.04

        Or

        https://github.com/FinOpsPP/Framework-Assessment/blob/main/components/actions/001.md
      render: Text
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Include information about what you expected to happen verses what actually happened, and things you tried.
      placeholder: Feel free to go "overboard" on the details. For us, the more details the better!
    validations:
      required: true