name: Enhancement
description: Request an enhancement on the project. Please open one issue per enhancement.
title: "[Enhancement]: "
labels: ["enhancement"]
type: enhancement
body:
  - type: checkboxes
    id: type-check
    attributes:
      label: What aspect of the Framework-Assessment would you like to enhance?
      options:
        - label: "assessments"
        - label: "specifications"
        - label: "tools"
        - label: "other"
    validations:
      required: true
  - type: checkboxes
    id: enhancement-check
    attributes:
      label: What type of enhancement is this?
      options:
        - label: "new feature"
        - label: "update feature"
        - label: "new documentations"
        - label: "update documentation"
        - label: "new profile"
        - label: "update profile"
        - label: "new components"
        - label: "update components"
    validations:
      required: true
  - type: textarea
    id: enhancement-description
    attributes:
      label: Enhancement Description
      description: Please let us know what you would like enhanced, and any proposals you have to produce the enhancement.
      placeholder: Feel free to go "overboard" on the details. For us, the more details the better!
    validations:
      required: true