title: FinOps++
description: Home of the Open Source FinOps++ Assessments
theme: jekyll-theme-cayman
baseurl: '/Framework-Assessment'
nav_links:
  - title: Home
    url: /Framework-Assessment/index.html
  - title: Assessments
    url: /Framework-Assessment/assessments/
  - title: Components
    url: /Framework-Assessment/components/
  - title: Specifications
    url: /Framework-Assessment/specifications/
  - title: Guidelines
    url: /Framework-Assessment/guidelines/
exclude:
  - create.sh
  - "**/.gitkeep"
include:
  - guidelines/contributing.md
disable_disk_cache: true