title: FinOps++
description: Home of the Open Source FinOps++ Assessments
theme: jekyll-theme-cayman
baseurl: ''
nav_links:
  - title: Home
    url: /index.html
  - title: Assessments
    url: /assessments/
  - title: Components
    url: /components/
  - title: Specifications
    url: /specifications/
  - title: Guidelines
    url: /guidelines/
exclude:
  - create.sh
  - "**/.gitkeep"
include:
  - guidelines/contributing.md
disable_disk_cache: true