[basic]
name = "example"
version = "0.0.1"

[profile]
title = "Finops++"
version = "0.0.1"
status = "Proposed"

[weights]
# default set of weight variables that can be overwritten based on need
1.6.102-draft-policies = 1.0
1.6.103-publish-guideline = 1.0
1.6.104-educate-policy = 1.0
1.6.105-compliance-report = 1.0
1.6.106-iterate-policies = 1.0
1.9.113-define-assess = 1.0
1.9.114-collect-standard = 1.0
1.9.115-establish-baseli = 1.0
1.9.116-actions-roadmap = 1.0
1.9.117-reassess-progres = 1.0
1.10.97-assess-skills = 1.0
1.10.98-develop-role = 1.0
1.10.99-offer-certification = 1.0
1.10.100-leverage-vendor = 1.0
1.10.101-track-training = 1.0
1.11.91-define-org = 1.0
1.11.92-implement-roadmap = 1.0
1.11.93-integrate-cost = 1.0
1.11.94-publish-finops = 1.0
1.11.95-drive-stakeholder = 1.0
1.11.96-automate-tasks = 1.0
1.12.124-assess-tooling = 1.0
1.12.125-evaluate-build = 1.0
1.12.126-implement-config = 1.0
1.12.127-train-users = 1.0
1.12.128-monitor-adoption = 1.0
1.14.129-establish-collab = 1.0
1.14.130-align-goals = 1.0
1.14.131-share-reporting = 1.0
1.14.132-provide-metrics = 1.0
1.14.133-coordinate-policy = 1.0
1.14.134-drive-adoption = 1.0
1.15.107-map-invoices = 1.0
1.15.108-reconcile-rates = 1.0
1.15.109-design-chargeback = 1.0
1.15.110-automate-chargeback = 1.0
1.15.111-chargeback-report = 1.0
1.15.112-resolve-variance = 1.0
1.23.136-exec-sponsor = 1.0
1.23.137-decision-rights = 1.0
1.23.138-multiyear-invest = 1.0
1.23.139-decision-cadence = 1.0
2.3.61-architecture-review = 1.0
2.3.62-assess-workloads = 1.0
2.3.63-estimate-trades = 1.0
2.3.64-iteratively-measure = 1.0
2.3.65-publish-benefits = 1.0
2.3.66-strengthen-arch = 1.0
2.3.118-create-workload = 1.0
2.3.119-define-success = 1.0
2.3.120-enforce-tagging = 1.0
2.3.121-align-timelines = 1.0
2.3.122-start-lower = 1.0
2.3.123-review-outcomes = 1.0
2.7.85-agg-emissions-data = 1.0
2.7.86-sustainability-metrics = 1.0
2.7.87-carbon-impact = 1.0
2.7.88-carbon-aware-guidance = 1.0
2.7.89-improve-eco-data = 1.0
2.7.90-sustainability-cost = 1.0
2.16.73-inventory-license = 1.0
2.16.74-document-license = 1.0
2.16.75-integrate-billing = 1.0
2.16.76-validate-utilization = 1.0
2.16.77-influence-workloa = 1.0
2.16.78-publish-license = 1.0
2.19.79-document-commit = 1.0
2.19.80-build-commitment = 1.0
2.19.81-purchase-commit = 1.0
2.19.82-track-roi = 1.0
2.19.83-allocate-upfront = 1.0
2.19.84-leverage-spot = 1.0
2.22.67-define-strategy = 1.0
2.22.68-inventory-classify = 1.0
2.22.69-collect-metrics = 1.0
2.22.70-scheduling-actions = 1.0
2.22.71-gamify-adoption = 1.0
2.22.72-track-kpis = 1.0
3.4.49-select-kpis = 1.0
3.4.50-validate-tagging = 1.0
3.4.51-choose-benchmarks = 1.0
3.4.52-stand-benchmarks = 1.0
3.4.53-track-trends = 1.0
3.4.54-translate-gaps = 1.0
3.5.43-define-budgeting = 1.0
3.5.44-integrate-rolling = 1.0
3.5.45-allocation-coverage = 1.0
3.5.46-publish-budget = 1.0
3.5.47-budget-alerts = 1.0
3.5.48-review-adapt = 1.0
3.13.37-forecast-approach = 1.0
3.13.38-collect-drivers = 1.0
3.13.39-run-forecasts = 1.0
3.13.40-compare-variance = 1.0
3.13.41-automate-variance = 1.0
3.13.42-feed-learnings = 1.0
3.18.30-define-estimating = 1.0
3.18.31-agree-pricing = 1.0
3.18.32-select-estimation = 1.0
3.18.33-sustainability-impact = 1.0
3.18.34-scenario-process = 1.0
3.18.35-report-accuracy = 1.0
3.18.36-coach-engineering = 1.0
3.21.55-define-units = 1.0
3.21.56-document-inputs = 1.0
3.21.57-build-unitcost = 1.0
3.21.58-set-cadence = 1.0
3.21.59-use-metrics = 1.0
3.21.60-communicate-wins = 1.0
Governance.Policy.102-draft-policies = 1.0
Governance.Policy.103-publish-guideline = 1.0
Governance.Policy.104-educate-policy = 1.0
Governance.Policy.105-compliance-report = 1.0
Governance.Policy.106-iterate-policies = 1.0